title: Squirrely Girl Produce
email: squirrely.girl.produce@gmail.com
description: >
  Hobby farm exploring Joel Salatin's pastured poultry techniques
  with ducks and geese.
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
repository: sgproduce/sgproduce.github.io
collections:
  plans:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
gems:
  - jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

timezone: America/New_York

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/posts"
    values:
      layout: "post"
