title: Squirrelly Girl Produce
email: squirrelly.girl.produce@gmail.com
description: Turning grass into eggs through portable pens on pasture
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
repository: sgproduce/sgproduce.github.io
collections:
  ideas:
    output: true
  plans:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
plugins:
  - jekyll
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

timezone: America/New_York

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "/posts"
    values:
      layout: "post"
